---

- name: test
  hosts: all
  become: no

  tasks:
    
    - block: #=====copy=====
      - name: Copy src
        copy:
          src: ../target/Calculator-1.0-SNAPSHOT.jar
          dest: /home/mftiedu/zimenkov/jenkins/Application.jar

...