apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: server-pod
      labels:
        app: server
    spec:
      containers:
      - image: zimenkov/server
        name: server
        ports:
        - containerPort: 9090
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: client-pod
      labels:
        app: client
    spec:
      containers:
      - image: zimenkov/client
        name: client
        imagePullPolicy: Always